name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - script:
        name: Set git config core.quotePath to false for emoji filenames
        code: git config --global core.quotePath false
      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main  # deploying branch
          cname: myeongjae.wiki
